### ISSUE TITLE
ncbi-parse-gff error:

### ISSUE THREAD

**Issue by ypchan** [biocommons/uta#225]

**Comment by ypchan** [comment]
![image](https://user-images.githubusercontent.com/33273919/79817160-654cb080-83b7-11ea-9b90-0e79e6bbc2a2.png)
Dear sir, 

Your script **ncbi-parse-gff** doesn't work. the error raise at **line 262**. You should replace **ti.ac** with **ti['ac']**. 

Thank for your great work.

**Comment by reece** [comment]
This problem is actually somewhat deeper. The problem is that the iterators that worked with Python 2 don't work with Python 3. The changes themselves are fairly simple, but I don't have time to test them. I may have additional UTA work in the near future, including reloading, so this change will come then.
